Repository wecode-bootcamp-korea/18-1st-LINEAVENGERS-backend, pull requests merged in 2021-03, with the labels that each got.

#2 [18기 김규동] Modify : 다대다 관계, ManyToManyField로 변경 / Cart클래스 is_order 삭제
  account/__init__.py
  account/admin.py
  account/apps.py
  account/migrations/0001_initial.py
  account/migrations/0002_user_order_place.py
  account/migrations/__init__.py
  account/models.py
  account/tests.py
  account/views.py
  lineavengers/settings.py
  mypage/__init__.py
  mypage/admin.py
  mypage/apps.py
  mypage/migrations/0001_initial.py
  mypage/migrations/0002_auto_20210318_1217.py
  mypage/migrations/__init__.py
  mypage/models.py
  mypage/tests.py
  mypage/views.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/0002_order_order_paytypes.py
  order/migrations/0003_remove_cart_is_order.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_product_sizes.py
  product/migrations/0003_product_questioners.py
  product/migrations/0004_product_order_product.py
  product/migrations/0005_auto_20210318_1026.py
  product/migrations/0006_auto_20210318_1217.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
Labels: Status: 리뷰 요청

#4 [김규동] 회원가입 수정, 로그인 기능 추가, utils.py 추가 후 데코레이터 작성
  account/migrations/0001_initial.py
  account/migrations/0002_user_order_place.py
  account/models.py
  account/urls.py
  account/utils.py
  account/views.py
  lineavengers/settings.py
  lineavengers/urls.py
  mypage/migrations/0001_initial.py
  mypage/migrations/0002_auto_20210318_1217.py
  mypage/migrations/0002_auto_20210319_1132.py
  mypage/models.py
  mypage/views.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210319_1132.py
  order/migrations/0002_order_order_paytypes.py
  order/migrations/0003_remove_cart_is_order.py
  order/models.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210319_1133.py
  product/migrations/0002_product_sizes.py
  product/migrations/0003_product_questioners.py
  product/migrations/0004_product_order_product.py
  product/migrations/0005_auto_20210318_1026.py
  product/migrations/0006_auto_20210318_1217.py
  product/models.py
Labels: Status: 리뷰 요청

#6 [김규동] 회원가입시 이메일 인증 추가, 회원가입시 아이디 실시간 중복검사 추가 / 리뷰 기능 구현중
  account/text.py
  account/urls.py
  account/views.py
  lineavengers/settings.py
  mypage/urls.py
  product/models.py
Labels: Status: Accepted

#8 [김규동] 데코레이터 수정, main에서 pull 후 merge 완료
  account/migrations/0001_initial.py
  account/utils.py
  account/views.py
  product/models.py
Labels: Status: Accepted

#10 [박국현] 상품 앱 model.py 수정 완료(urgent)
  account/migrations/0001_initial.py
  mypage/migrations/0002_auto_20210321_0210.py
  mypage/migrations/0002_auto_20210323_0704.py
  order/migrations/0002_auto_20210321_0210.py
  order/migrations/0002_auto_20210323_0704.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210319_1133.py
  product/models.py
Labels: Status: Accepted

#9 [김규동] 깃허브 리뷰 적용 완료, mypage/views/py 리뷰보기 기능 추가 / 장바구니 조회 기능 구현중
  .vscode/settings.json
  account/migrations/0001_initial.py
  account/utils.py
  account/views.py
  lineavengers/urls.py
  mypage/migrations/0001_initial.py
  mypage/migrations/0002_auto_20210324_0243.py
  mypage/urls.py
  mypage/views.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210324_0243.py
  product/migrations/0001_initial.py
  product/models.py
Labels: Status: Accepted

#11 [김규동] mypage/views.py Favorite클래스 get 수정
  mypage/views.py
Labels: Status: Accepted

#13 [박국현] 찜, 추천 여부 확인을 위한 status_decorator 추가.
  account/utils.py
  product/views.py
Labels: Status: Accepted

#15 [김규동] 로그인 수정
  account/views.py
Labels: Status: Accepted

#12 [박국현] 주문 앱 장바구니 담기, 장바구니 주문, 상품 주문 기능 추가 및 에러로 인한 재수정 완료.
  lineavengers/urls.py
  mypage/migrations/0002_auto_20210324_0243.py
  mypage/urls.py
  order/migrations/0002_auto_20210324_0243.py
  order/migrations/0003_auto_20210325_1025.py
  order/models.py
  order/urls.py
  order/views.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#14 [김규동] 장바구니 삭제 기능 수정
  account/utils.py
  order/views.py
Labels: Status: Accepted

#17 [박국현] 최종 서비스 확인 후 오류사항 수정 *URGENT*
  account/utils.py
  mypage/views.py
  order/views.py
  product/views.py
Labels: Status: 도움 요청, Status: 리뷰 요청
